name: STM32 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install CppCheck, Make, & ARM_GCC
      run: |
        sudo apt install cppcheck
        sudo apt install make
        yes | sudo apt install gcc-arm-none-eabi
        whereis make
        
    - run: make
    - run: make cppcheck
