name: STM32 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3        
      
    - name: Install CppCheck, Make, & ARM_GCC
      run: |
        sudo apt install cppcheck -y
        sudo apt install make -y
        sudo apt install doxygen -y
        sudo apt install gcc-arm-none-eabi -y
        
    - run: make
    - run: make cppcheck

    - name: Run Doxygen
      run: |
        cd ./Docs/DoxygenDocs
        Doxygen

    #- uses: mattnotmitt/doxygen-action@v1.9.5
    #  with: 
    #    working-directory: "./Docs/DoxygenDocs"
    #    doxyfile-path: "Doxyfile"
    #    enable-latex: true

    - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        folder: "./Docs/DoxygenDocs/html"
        target_folder: "./public"
    
    #- name: Deploy Doxygen Docs
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{secrets.GITHUB_TOKEN}}
    #    publish_dir: ./public

